### ISSUE TITLE
怎么进入网页啊

### ISSUE THREAD

**Issue by LitterProgramer** [jitwxs/express-ssm#1]
项目成功启动了,但是怎么进入网页?

**Comment by LitterProgramer** [comment]
好了

**Comment by Du2018** [comment]
我导入项目了之后 编译器说 java: 程序包com.baomidou.mybatisplus.generator不存在该怎么解决啊

**Comment by Tenthousand168** [comment]
> 项目成功启动了,但是怎么进入网页?

可以加个联系方式吗，想请教一下，我的QQ1490865478.

**Comment by zhongchonghe** [comment]
> 好了
项目启动失败，报错可以请教一下吗

**Comment by jitwxs** [comment]
README 已经补充详细的启动流程，如有疑问，请再重新提问。

**Comment by zhongchonghe** [comment]
能运行起来嘛？加我q1361934810






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jitwxs"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 晚上11:11
收件人: "jitwxs/express-ssm"<express-ssm@noreply.github.com&gt;; 
抄送: "1361934810"<1361934810@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jitwxs/express-ssm] 怎么进入网页啊 (#1)





 
Closed #1.

**Comment by LitterProgramer** [comment]
可以了，谢谢啦，很感谢你的项目


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: zhongchonghe <notifications@github.com&gt;
发送时间: 2020年4月23日 23:19
收件人: jitwxs/express-ssm <express-ssm@noreply.github.com&gt;
抄送: LitterProgramer <1615211669@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[jitwxs/express-ssm] 怎么进入网页啊 (#1)





 能运行起来嘛？加我q1361934810 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "jitwxs"<notifications@github.com&amp;gt;;  
 发送时间: 2020年4月23日(星期四) 晚上11:11 
 收件人: "jitwxs/express-ssm"<express-ssm@noreply.github.com&amp;gt;;  
 抄送: "1361934810"<1361934810@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [jitwxs/express-ssm] 怎么进入网页啊 (#1) 
 
 
 
 
 
   
 Closed #1.
