### ISSUE TITLE
无法登陆，而且页面不像演示页面那样

### ISSUE THREAD

**Issue by McKenzieIT** [jitwxs/express-ssm#2]
一开始的页面没有像演示页面那样自适应，全堆在左边

**Comment by Du2018** [comment]
我导入项目了之后 编译器说 java: 程序包com.baomidou.mybatisplus.generator不存在该怎么解决啊

**Comment by wushirong540** [comment]
我的也是页面都在左边，想问问你是怎么解决的 @McKenzieIT

**Comment by jitwxs** [comment]
README 已经补充详细的启动流程，如有疑问，请再重新提问。
